/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_op: () => import("@/views/log/op/index.vue"),
  manage_config: () => import("@/views/manage/config/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "operation_abnormal-order": () => import("@/views/operation/abnormal-order/index.vue"),
  "operation_noc-info": () => import("@/views/operation/noc-info/index.vue"),
  "operation_order-info": () => import("@/views/operation/order-info/index.vue"),
  "operation_order-msg": () => import("@/views/operation/order-msg/index.vue"),
  other_data: () => import("@/views/other/data/index.vue"),
  other_string: () => import("@/views/other/string/index.vue"),
  "prod-config_config-script": () => import("@/views/prod-config/config-script/index.vue"),
  "prod-config_prod-info": () => import("@/views/prod-config/prod-info/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
