# 运行端口
server:
  port: 8848
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 数据源
spring:
  application:
    name: crm-om
  datasource:
    # 多数据源配置
    dynamic:
      # 设置默认的数据源(默认master)
      primary: master
      # 严格匹配数据源(默认false)
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-bp1fodey2m8m8390cto.mysql.rds.aliyuncs.com:3306/icu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
          username: learn
          password: Learn_MySQL
          hikari:
            # 池中维护的最小空闲连接数
            minimum-idle: 10
            # 池中最大连接数，包括闲置和使用中的连接
            maximum-pool-size: 20
            idleTimeout: 86400
            maxLifetime: 86400

# mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

# logger 打印调整
logging:
  level:
    com.zaxxer.hikari.HikariConfig: debug

# JWT 配置
jwt:
  # 密钥
  signKey: crm!2024#om
  # 有效期偏移量(秒)
  expired: 3600
  authPrefix: 'Bearer '
  authName: Authorization

# 自定义参数
custom:
  dynamic:
    enable: true

# 开启增强
knife4j:
  enable: true
  setting:
    enable-swagger-models: true
    swagger-model-name: 参数模型